name: Feature Request
description: Suggest a new feature or enhancement for Juno
title: '[Feature]: '
labels: ['enhancement', 'triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Describe the problem.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe how you envision this feature working
      placeholder: Describe your proposed solution...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Have you considered any alternative solutions or workarounds?
      placeholder: Describe alternative solutions you've considered...

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases for this feature
      placeholder: |
        1. Use case 1: [Description]
        2. Use case 2: [Description]
        3. Use case 3: [Description]
    validations:
      required: true

  - type: textarea
    id: benefits
    attributes:
      label: Benefits
      description: How will this feature benefit users or the project?
      placeholder: |
        - Benefit 1
        - Benefit 2
        - Benefit 3
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact
      description: What type of users would benefit from this feature?
      options:
        - All users
        - Developers integrating Juno
        - Organisation administrators
        - End users
        - API consumers
        - Other
    validations:
      required: true

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about implementation, share them here
      placeholder: Technical implementation ideas...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or mockups
      placeholder: Add any other context here...

  - type: checkboxes
    id: willing-to-help
    attributes:
      label: Contribution
      description: Would you be willing to help implement this feature?
      options:
        - label: I would be willing to submit a pull request for this feature
        - label: I would be willing to help test this feature

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: I have included all the requested information
          required: true
